;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        delete-horizontal-space
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        indent-for-tab-command
        kill-region
        mark-sexp
        mark-word
        markdown-outdent-or-delete
        paredit-delete-char
        paredit-semicolon
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        backward-sentence
        markdown-cycle
        ))
